### ISSUE TITLE
도커 베스트 프랙티스 (번역) - CH DEVLOG

### ISSUE THREAD

**Issue by changhoi** [changhoi/changhoi.github.io#7]
https://changhoi.github.io/posts/docker/Docker-best-practices/ 

 깃헙에는 현재 백만이 넘는 도커파일들이 있다. 하지만 모든 도커파일들이 동일하지는 한다. 효율성은 중요한 것이고, 이번 블로그 시리즈는 도커파일의 다섯가지 영역: 빌드 시간의 증가, 이미지의 사이즈, 유지성, 보안, 반복성에 있어서 베스트 프랙티스를 다룰 것이다. 만약 독자가 도커에 막 시작하는 사람이라면, 이 글은 독자를 위한 글이다! 이후 시리즈는 좀

**Comment by JeongHyeongKim** [comment]
좋은 번역 감사합니다 :)
